### ISSUE TITLE
Preserve user in version history instead of System User

### ISSUE THREAD

**Issue by CesarCapillas** [keensoft/alfresco-version-by-name#1]
Hi:

First of all, thank you very much for this contribution. It is a common question (and wish) for many Alfresco end users, this version behaviour.

During our tests in Alfresco 5.1.e,  we checked that new versions are done with "System User", instead of the user of the current session.

Is it possible to use the current user session instead of a System one ? 

Thanks in advance and best regards.

--C.

**Comment by angelborroy** [comment]
Sure, I'll publish in twi weeks the version developed in the video (https://www.youtube.com/watch?v=ekPyWLFmip0), which is cleaner and behaves like you are describing.

However, you can try before, just follow the video and you'll find it pretty easy.

Thanks for your interest.

**Comment by CesarCapillas** [comment]
Thanks for the quick answer and the video reference, Angel. I'll check it.

Kind Regards.

--C.

**Comment by angelborroy-ks** [comment]
Version 1.1.0 is available including right version history.

**Comment by CesarCapillas** [comment]
Muchas gracias Angel, te hago de beta tester y te digo ;)
Lo usamos internamente mucho, por cierto el video esta muy bien, muy ilustrativo.

Saludos.

--C.

**Comment by CesarCapillas** [comment]
Tested in Alfresco 5.1.e

Kind regards.

--C.
