### ISSUE TITLE
Site activities show that you added a file with "-1" in the name

### ISSUE THREAD

**Issue by CesarCapillas** [keensoft/alfresco-version-by-name#2]
Hi Angel:

First of all, thanks again for the addon. 
Only a question, I don't know if you can reproduce it. 
May the site activities be recording that you added a file with "-1" in the name ?

Regards.

--C.

**Comment by angelborroy-ks** [comment]
Right.

We're leaving this issue open to solve it in the next release.

Thanks

**Comment by CesarCapillas** [comment]
Thanks Angel:

FYI: Take into consideration that nodes for the links in the dashlet and also in email notification no longer exist in the repository.

Best regards.

--C.

**Comment by angelborroy-ks** [comment]
Thanks for your collaboration on improving this addon, your comments are useful.

It was not so easy to fix that, but it should work from now.

Please, validate 1.1.1 release.

**Comment by CesarCapillas** [comment]
Thanks again Angel:

I tested locally in Alfresco 5.1.g and now it looks better. 
The links are now fine, there are not wrong activities but I'm not sure, if there is no document "updates" in Site activities when using this addon (as it is when uploading a new version). I think it is not easy, because the internal logic of the new behaviour is not (or has to be) mapped directly with the site activity events. I do not know if this is possible.

Best Regards.

--C.

**Comment by angelborroy-ks** [comment]
Nice to have a such skilled "beta-tester"!

I've solved it by compensating the activity post. Maybe it's not the better approach, but it will do the job.

I've not created a new 1.1.1 as it was incomplete, so you have the last changes have been merged to that 1.1.1 and it has been republished for your convenience.

Thanks again.

**Comment by CesarCapillas** [comment]
Now it works. Thank you very much Angel for the pretty fast fix.

Best regards.

--C.
